### ISSUE TITLE
Use Crowdin Translation Collaboration Platform

### ISSUE THREAD

**Issue by Littlegolden** [flarum/docs#177]
Advantages:
- Visual online editor with real-time preview of translation results.
- Integration with github to automatically update source documents and synchronize translation results.
- Multiple branches (i.e. multiple versions) can be translated at the same time, and the translation results can be applied on multiple branches at the same time.

and the most one:
- Open source projects have free access to premium features. https://crowdin.com/page/open-source-project-setup-request

Official website : https://crowdin.com/

**Comment by askvortsov1** [comment]
I've never used this, but if it works well for long form content, I'm 100% for it.

**Comment by matteocontrini** [comment]
> I've never used this, but if it works well for long form content, I'm 100% for it.

I use it, and unless I'm missing a feature or part of the product, it's not, actually... Also because, for example, the history of translations is not shown as a diff but as a list of revisions, which is definitely unsuitable for long content.

**Comment by askvortsov1** [comment]
Ah, that's unfortunate. I was hoping for something similar with weblate (https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/22), but looks like that has the same issue.

**Comment by luceos** [comment]
Hosted weblate might be an option, it's free for foss: https://weblate.org/en/hosting/

**Comment by askvortsov1** [comment]
Problem is, we need something that works well for long-form content (or that intelligently splits and re-assembles long form content). Weblate doesn't currently handle this: https://github.com/WeblateOrg/weblate/issues/3106

**Comment by scvoet** [comment]
Hi, I have created an example of document translation work with the help of a localization platform. I have used transifex, which is a good experience and free for open source projects.

Now you can try to work on the translation via transifex.
https://www.transifex.com/flarum/docs-10/

Also I will briefly talk about the implementation logic. I created [a test repository on GitHub](https://github.com/scvoet/flarum-docs-tests) and integrated it with the transifex project. Configure the path to the original text and the path to the translation, and then start the translation. When the translation is done, a push will be automatically initiated.

The rules are very simple to configure, and I'll publish them here as well.

```yaml
filters:
  - filter_type: dir
    file_format: GITHUBMARKDOWN
    source_file_extension: md
    source_language: en
    source_file_dir: docs
    translation_files_expression: 'docs/<lang>'
  - filter_type: dir
    file_format: GITHUBMARKDOWN
    source_file_extension: md
    source_language: en
    source_file_dir: docs/extend 
    translation_files_expression: 'docs/<lang>/extend'
  - filter_type: dir
    file_format: GITHUBMARKDOWN
    source_file_extension: md
    source_language: en
    source_file_dir: docs/.vuepress/config/locales/en
    translation_files_expression: 'docs/.vuepress/config/locales/<lang>'
```
