### ISSUE TITLE
Recommend the use of Less namespaces for extensions

### ISSUE THREAD

**Issue by davwheat** [flarum/docs#322]
To prevent any mixin collisions between extensions, we should recommend the use of Less namespaces, similar to how we handle initiali(s/z)ers in JS.

https://lesscss.org/features/#mixins-feature-namespaces

They're not _that_ tricky to understand, thankfully, using an ID-based system.

```less
#davwheat__sidebar-nav-items {
  .my-cool-mixin() {
    color: red;
  }
}

button.davwheat_btn {
  #davwheat__sidebar-nav-items.my-cool-mixin();
}
```
